from nicegui import ui

from core.auth import require_app_access
from core.theme import Theme


GAME_HTML = r'''
<div id="ge-app" class="ge-app">
  <section id="ge-home" class="ge-home">
    <div class="ge-hero"><small>TACTICAL TERRITORY BATTLE</small><h1>GRID<br><em>EMPIRE</em></h1><p>島を奪い、敵の首都を制圧せよ。</p></div>
    <div class="ge-player-select"><span>参加勢力</span><button class="active" data-players="2">2</button><button data-players="3">3</button><button data-players="4">4</button></div>
    <div class="ge-stage-title"><b>ステージを選択</b><span>STAGE SELECT</span></div>
    <div class="ge-stages">
      <button data-stage="0"><i>01</i><div><b>はじまりの島</b><span>小さな島で基本を覚える</span></div><strong>かんたん</strong></button>
      <button data-stage="1"><i>02</i><div><b>分断海峡</b><span>狭い道をどう突破するか</span></div><strong>ふつう</strong></button>
      <button data-stage="2"><i>03</i><div><b>決戦大陸</b><span>強大な敵との全面戦争</span></div><strong>むずかしい</strong></button>
    </div>
    <div class="ge-level-soon"><span>COMMANDER LEVEL</span><b>レベル機能は今後追加予定</b></div>
  </section>
  <section id="ge-game" class="ge-game">
    <div class="ge-top"><button id="ge-home-button" class="ge-back">‹</button><div><b>GRID EMPIRE</b><small id="ge-stage-name">領土戦線</small></div><button id="ge-restart" class="ge-restart">↻</button></div>
    <div class="ge-score"><div class="blue"><span>自軍</span><b id="ge-blue">0</b></div><div class="turn"><b id="ge-state">戦闘開始</b><small id="ge-hint">自分のマスを選択</small></div><div class="red"><span>敵勢力</span><b id="ge-red">0</b></div></div>
    <div id="ge-factions" class="ge-factions"></div>
    <div class="ge-force"><span>出撃兵力</span><button data-ratio=".3">30%</button><button class="active" data-ratio=".5">50%</button><button data-ratio=".7">70%</button><button data-ratio="1">全軍</button></div>
    <div class="ge-board-wrap"><div id="ge-board" class="ge-board"></div></div>
    <div class="ge-legend"><span><i class="blue"></i>自軍</span><span><i class="red"></i>赤軍</span><span><i class="yellow"></i>黄軍</span><span><i class="purple"></i>紫軍</span><span><i class="neutral"></i>未占領</span><span>★ 首都</span></div>
    <div class="ge-terrain-note"><span>▲ 山：防御＋50%</span><span>◆ 都市：成長＋1</span><span>♣ 森：敵兵力を隠す</span><span>⚓ 港：海路で接続</span><span>⚠ 補給切れ：成長停止</span></div>
    <div class="ge-help"><b>遊び方</b><span>青い地域を選び、道路でつながる地域へ進軍。数字は兵力。敵の★首都をすべて奪えば勝利。</span></div>
  </section>
  <div id="ge-modal" class="ge-modal"><div><b id="ge-result"></b><span id="ge-result-sub"></span><button id="ge-again">もう一度</button><button id="ge-stage-select" class="sub">ステージ選択</button></div></div>
</div>
'''


GAME_CSS = r'''
<style>
body{margin:0;background:#081525!important;color:#fff;overscroll-behavior:none}.nicegui-content{padding:0!important}
.ge-app{min-height:100dvh;background:radial-gradient(circle at 50% 0,#163252 0,#081525 48%,#050b14 100%);font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif;padding:env(safe-area-inset-top) 12px calc(18px + env(safe-area-inset-bottom));box-sizing:border-box}
.ge-game{display:none}.ge-home{max-width:720px;margin:auto;padding:18px 4px}.ge-hero{padding:54px 8px 30px}.ge-hero small{font-size:10px;letter-spacing:.24em;color:#56b8ff}.ge-hero h1{font-size:58px;line-height:.78;margin:13px 0 20px;letter-spacing:-.06em}.ge-hero h1 em{font-style:normal;color:#4db6ff}.ge-hero p{color:#91a5b8;font-size:13px}.ge-stage-title{display:flex;align-items:end;justify-content:space-between;margin:0 5px 10px}.ge-stage-title b{font-size:16px}.ge-stage-title span{font-size:9px;letter-spacing:.16em;color:#6d8298}.ge-stages{display:grid;gap:9px}.ge-stages button{width:100%;border:1px solid #29435f;background:linear-gradient(135deg,#122943,#0c1e33);color:white;border-radius:18px;padding:14px;display:grid;grid-template-columns:52px 1fr auto;align-items:center;text-align:left;gap:11px;touch-action:manipulation}.ge-stages button:active{transform:scale(.98);filter:brightness(1.4)}.ge-stages i{font-style:normal;font-size:25px;font-weight:900;color:#4db6ff;border-right:1px solid #2a435d}.ge-stages b,.ge-stages span{display:block}.ge-stages b{font-size:15px}.ge-stages span{font-size:10px;color:#8fa3b7;margin-top:3px}.ge-stages strong{font-size:9px;color:#e5c65b;background:#493e20;padding:5px 7px;border-radius:8px}.ge-stages button:nth-child(2) strong{color:#77d8ff;background:#153e50}.ge-stages button:nth-child(3) strong{color:#ff8b91;background:#4c232a}.ge-level-soon{margin-top:14px;border:1px dashed #29435f;border-radius:16px;padding:13px 16px;color:#74899d}.ge-level-soon span,.ge-level-soon b{display:block}.ge-level-soon span{font-size:8px;letter-spacing:.18em}.ge-level-soon b{font-size:11px;margin-top:3px}
.ge-player-select{display:grid;grid-template-columns:1fr repeat(3,46px);gap:6px;align-items:center;margin:0 5px 22px;padding:9px 10px;border:1px solid #29435f;border-radius:14px;background:#0c1e33}.ge-player-select span{font-size:11px;color:#91a5b8}.ge-player-select button{border:1px solid #29435f;border-radius:9px;background:#10233a;color:#8fa3b7;font-weight:900;padding:7px}.ge-player-select button.active{background:#217fc0;border-color:#55baff;color:white}
.ge-top{max-width:760px;margin:auto;height:70px;display:grid;grid-template-columns:48px 1fr 48px;align-items:center;text-align:center}.ge-top b{font-size:18px;letter-spacing:.12em}.ge-top small{display:block;color:#7f94ab;font-size:10px;letter-spacing:.22em;margin-top:2px}.ge-back,.ge-restart{height:42px;border:1px solid #29435f;border-radius:14px;background:#10233a;color:#dceeff;font-size:28px}.ge-restart{font-size:22px}
.ge-score{max-width:740px;margin:4px auto 12px;display:grid;grid-template-columns:1fr 1.35fr 1fr;gap:8px}.ge-score>div{border:1px solid #263d56;background:rgba(12,28,47,.88);border-radius:15px;padding:9px 12px}.ge-score span,.ge-score small{font-size:10px;color:#91a5b8;display:block}.ge-score b{font-size:20px}.ge-score .blue{border-color:#237ac0}.ge-score .blue b{color:#4db6ff}.ge-score .red{text-align:right;border-color:#a53f47}.ge-score .red b{color:#ff6b70}.ge-score .turn{text-align:center}.ge-score .turn b{font-size:13px}.ge-score .turn small{margin-top:3px}
.ge-force{max-width:720px;margin:0 auto 9px;display:grid;grid-template-columns:1fr repeat(4,54px);gap:5px;align-items:center}.ge-force span{font-size:10px;color:#8297aa}.ge-force button{border:1px solid #29435f;border-radius:9px;background:#10233a;color:#8da2b5;font-size:10px;font-weight:800;padding:7px 2px;touch-action:manipulation}.ge-force button.active{background:#217fc0;border-color:#55baff;color:white;box-shadow:0 0 12px #248bd866}
.ge-board-wrap{max-width:740px;margin:auto;border:1px solid #29435f;border-radius:22px;padding:7px;background:#07182a;box-shadow:0 20px 60px #0008;overflow:hidden}.ge-board{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:2px;aspect-ratio:10/8;background:radial-gradient(circle at 40% 30%,#164b6a,#08233b 70%);border-radius:16px;overflow:hidden}.ge-cell{position:relative;border:0;border-radius:4px;color:#fff;font-weight:900;font-size:13px;box-shadow:inset 0 0 0 1px #ffffff12;transition:transform .08s,filter .08s;touch-action:manipulation;-webkit-tap-highlight-color:transparent;user-select:none;padding:0}.ge-cell:active{transform:scale(.82);filter:brightness(1.6)}.ge-cell.water{pointer-events:none;background:linear-gradient(145deg,#0c3855,#0a2944);box-shadow:inset 0 0 12px #1e6e9133}.ge-cell.land.plain{background:linear-gradient(145deg,#658569,#465f4b)}.ge-cell.land.forest{background:linear-gradient(145deg,#315f46,#203f34)}.ge-cell.land.mountain{background:linear-gradient(145deg,#77776f,#4f514e)}.ge-cell.land.city{background:linear-gradient(145deg,#957a45,#615332)}.ge-cell.blue{background:linear-gradient(145deg,#2699e9,#155d9a)!important}.ge-cell.red{background:linear-gradient(145deg,#e3565e,#922c39)!important}.ge-cell.selected{outline:3px solid #fff;outline-offset:-3px;z-index:2;transform:scale(.9);filter:brightness(1.35);animation:geselect .75s infinite alternate}.ge-cell.target{filter:brightness(1.45);box-shadow:inset 0 0 0 3px #f7d45e}.ge-cell.incoming{box-shadow:inset 0 0 0 3px #ffe16b;animation:geincoming .45s infinite alternate}.ge-power{position:relative;z-index:2;display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:22px;padding:0 3px;border-radius:8px;background:#07111dbb;text-shadow:0 1px 2px #000;font-size:12px}.ge-march{position:absolute;z-index:4;left:2px;right:2px;bottom:1px;border-radius:5px;background:#f3ca35;color:#101722;font-size:8px;line-height:13px;text-align:center;white-space:nowrap}.ge-cell:before{position:absolute;left:3px;bottom:1px;font-size:9px;opacity:.65}.ge-cell.forest:before{content:'♣'}.ge-cell.mountain:before{content:'▲'}.ge-cell.city:before{content:'◆';color:#ffe38b}.ge-cell.capital:after{content:'★';position:absolute;top:1px;right:3px;font-size:10px;color:#ffe27a;text-shadow:0 1px 2px #000}.ge-cell.hit{animation:gehit .24s}.ge-cell.claim{animation:geclaim .35s}@keyframes geselect{to{box-shadow:inset 0 0 0 3px #fff,0 0 14px #fff9}}@keyframes geincoming{to{filter:brightness(1.55)}}@keyframes gehit{50%{transform:scale(.72);filter:brightness(2)}}@keyframes geclaim{50%{transform:scale(1.18)}}
.ge-legend{max-width:720px;margin:10px auto 0;display:flex;justify-content:center;gap:14px;flex-wrap:wrap;color:#9cb0c2;font-size:10px}.ge-legend span{display:flex;align-items:center;gap:5px}.ge-legend i{display:block;width:10px;height:10px;border-radius:3px}.ge-legend i.blue{background:#268fd8}.ge-legend i.red{background:#d74c57}.ge-legend i.neutral{background:#58705c}
.ge-board-wrap{max-width:680px;border-radius:24px;padding:9px}.ge-board{grid-template-columns:repeat(8,minmax(0,1fr));gap:0;aspect-ratio:8/7;background:radial-gradient(circle at 35% 25%,#216886,#0a3552 48%,#061d32 100%);border-radius:18px;padding:3px}.ge-cell{border-radius:18% 32% 22% 28%;box-shadow:inset 0 1px 8px #ffffff18,inset 0 -5px 10px #0003;margin:-1px}.ge-cell:nth-child(3n){border-radius:32% 16% 28% 20%}.ge-cell:nth-child(4n){border-radius:20% 34% 16% 30%}.ge-cell.water{background:radial-gradient(circle at 30% 30%,#1a5774aa,#0a304a88 70%)}.ge-cell.land{z-index:1;outline:1px solid #d9e9cf18}.ge-cell.land.plain{background:radial-gradient(circle at 35% 30%,#789875,#405e48 76%)}.ge-cell.land.forest{background:radial-gradient(circle at 35% 30%,#417357,#1d4032 78%)}.ge-cell.land.mountain{background:radial-gradient(circle at 40% 25%,#97958a,#4b504c 72%)}.ge-cell.land.city{background:radial-gradient(circle at 35% 25%,#b39453,#625235 74%)}.ge-cell.blue{background:radial-gradient(circle at 35% 25%,#43b6f6,#135b9a 76%)!important}.ge-cell.red{background:radial-gradient(circle at 35% 25%,#f06d72,#922c39 76%)!important}.ge-cell.yellow{background:radial-gradient(circle at 35% 25%,#f4d45c,#9b7217 76%)!important}.ge-cell.purple{background:radial-gradient(circle at 35% 25%,#b982ee,#653890 76%)!important}.ge-power{min-width:25px;height:25px;border-radius:999px}.ge-cell.capital:after{top:3px;right:5px;font-size:12px}.ge-legend i.yellow{background:#d4ad2c}.ge-legend i.purple{background:#9556c9}.ge-factions{max-width:680px;margin:-4px auto 8px;display:flex;justify-content:center;gap:6px}.ge-factions span{font-size:9px;border-radius:7px;padding:3px 7px;background:#14263a;color:#9cb0c2}.ge-factions .r{color:#ff777d}.ge-factions .y{color:#f0cb45}.ge-factions .p{color:#c28bed}
.ge-help{max-width:720px;margin:12px auto 0;background:#10233a;border:1px solid #263d56;border-radius:14px;padding:11px 14px;display:flex;gap:12px;align-items:center}.ge-help b{white-space:nowrap;font-size:12px;color:#f2c650}.ge-help span{font-size:11px;line-height:1.5;color:#9cb0c2}
.ge-modal{display:none;position:fixed;inset:0;background:#020711dd;z-index:99;align-items:center;justify-content:center;padding:24px}.ge-modal.show{display:flex}.ge-modal>div{text-align:center;background:#10233a;border:1px solid #3c5875;border-radius:24px;padding:34px;width:min(340px,90vw);box-shadow:0 30px 80px #000}.ge-modal b{display:block;font-size:30px}.ge-modal span{display:block;color:#9eb0c2;margin:8px 0 24px}.ge-modal button{border:0;border-radius:14px;background:#2b98e7;color:white;font-weight:800;padding:13px 28px}.ge-modal button.sub{display:block;margin:9px auto 0;background:transparent;border:1px solid #3c5875;color:#9eb0c2}
@media(max-width:520px){.ge-app{padding-left:7px;padding-right:7px}.ge-board-wrap{padding:4px}.ge-board{gap:1px}.ge-score{grid-template-columns:1fr 1.25fr 1fr}.ge-help{align-items:flex-start}.ge-power{min-width:20px;height:20px;font-size:11px}}
.ge-board{display:block;position:relative;aspect-ratio:800/520;padding:0;background:radial-gradient(ellipse at 45% 40%,#1b5b79,#082b46 58%,#061b2e 100%);overflow:hidden}.ge-map{display:block;width:100%;height:100%}.ge-region{cursor:pointer;touch-action:manipulation}.ge-region polygon{stroke:#d8ebd744;stroke-width:3;transition:filter .12s,stroke .12s}.ge-region.neutral polygon{fill:#567559}.ge-region.blue polygon{fill:#237fbd}.ge-region.red polygon{fill:#bc424d}.ge-region.yellow polygon{fill:#b89025}.ge-region.purple polygon{fill:#7946a1}.ge-region.selected polygon{stroke:#fff;stroke-width:8;filter:brightness(1.28)}.ge-region.target polygon{stroke:#ffe16b;stroke-width:7;filter:brightness(1.22)}.ge-region:active polygon{filter:brightness(1.55)}.ge-road{stroke:#d7c49788;stroke-width:5;stroke-linecap:round;stroke-dasharray:8 7;pointer-events:none}.ge-region-label{fill:#fff;font-weight:900;font-size:18px;text-anchor:middle;dominant-baseline:middle;pointer-events:none;text-shadow:0 2px 3px #000}.ge-place{fill:#e8f0e8cc;font-size:12px;font-weight:700;text-anchor:middle;pointer-events:none}.ge-terrain{font-size:16px;text-anchor:middle;pointer-events:none}.ge-capital{fill:#ffe57b;font-size:20px;text-anchor:middle;pointer-events:none}.ge-move-line{stroke:#ffe16b;stroke-width:8;stroke-linecap:round;stroke-dasharray:10 9;animation:gemarch .45s linear infinite;pointer-events:none}.ge-move-badge{fill:#ffe16b}.ge-move-text{fill:#101722;font-size:12px;font-weight:900;text-anchor:middle;dominant-baseline:middle;pointer-events:none}@keyframes gemarch{to{stroke-dashoffset:-19}}
.ge-board-wrap{max-width:760px;overflow:auto;-webkit-overflow-scrolling:touch;scrollbar-width:thin}.ge-board{min-width:860px;min-height:559px}.ge-region.unsupplied polygon{filter:saturate(.28) brightness(.68);stroke:#ff9a70;stroke-dasharray:8 6}.ge-supply{fill:#ffae7d;font-size:11px;font-weight:900;text-anchor:middle;pointer-events:none}.ge-sea-road{stroke:#61d4ff99;stroke-width:6;stroke-linecap:round;stroke-dasharray:4 11;pointer-events:none}.ge-region.fog .ge-region-label{fill:#c9d2d8}.ge-terrain-note{max-width:720px;margin:8px auto 0;display:flex;gap:6px;overflow:auto;padding-bottom:2px}.ge-terrain-note span{white-space:nowrap;font-size:9px;color:#94a8ba;border:1px solid #29435f;background:#10233a;border-radius:8px;padding:5px 7px}
</style>
'''


GAME_JS = r'''
<script>
if(false)setTimeout(()=>{
 const W=8,H=7,N=W*H,ARMIES=['b','r','y','p'],STAGES=[
  {name:'STAGE 01 · はじまりの島',map:['00111100','01111110','11111110','11111111','01111111','00111110','00011100'],starts:[[42,34,43],[14,13,22],[16,17,24],[39,38,31]],power:16,speed:1200},
  {name:'STAGE 02 · 分断海峡',map:['00111100','01101110','11111111','11011111','11111011','01111110','00111100'],starts:[[42,34,43],[14,13,22],[16,17,24],[39,38,31]],power:19,speed:950},
  {name:'STAGE 03 · 決戦大陸',map:['01111110','11111111','11111111','11111111','11111111','11111111','01111110'],starts:[[42,34,43],[14,13,22],[16,17,24],[39,38,31]],power:23,speed:720}
 ]; let cells=[],selected=-1,timer=null,aiTimer=null,marchTimer=null,ended=false,stageIndex=0,playerCount=2,ratio=.5,movements=[],cooldowns={},gameToken=0,aiTurn=0,defeated=new Set();
 const board=document.getElementById('ge-board'), state=document.getElementById('ge-state'), hint=document.getElementById('ge-hint'),home=document.getElementById('ge-home'),game=document.getElementById('ge-game');
 const neighbors=i=>{const x=i%W,y=Math.floor(i/W),a=[];if(x)a.push(i-1);if(x<W-1)a.push(i+1);if(y)a.push(i-W);if(y<H-1)a.push(i+W);return a};
 function showHome(){gameToken++;clearInterval(timer);clearInterval(aiTimer);clearInterval(marchTimer);ended=true;movements=[];document.getElementById('ge-modal').classList.remove('show');game.style.display='none';home.style.display='block'}
 function startStage(i){stageIndex=Number(i);home.style.display='none';game.style.display='block';init()}
 function init(){const s=STAGES[stageIndex];gameToken++;clearInterval(timer);clearInterval(aiTimer);clearInterval(marchTimer);ended=false;selected=-1;movements=[];cooldowns={};defeated=new Set();aiTurn=0;cells=Array.from({length:N},(_,i)=>{const land=s.map[Math.floor(i/W)][i%W]==='1';const terrain=!land?'water':i%11===0?'city':i%7===0?'mountain':i%4===0?'forest':'plain';return{o:land?'n':'w',p:land?1+Math.floor(Math.random()*5):0,c:false,co:'',t:terrain}});
  ARMIES.slice(0,playerCount).forEach((owner,k)=>{const pos=s.starts[k];Object.assign(cells[pos[0]],{o:owner,p:k? s.power:16,c:true,co:owner});Object.assign(cells[pos[1]],{o:owner,p:k?8:7});Object.assign(cells[pos[2]],{o:owner,p:k?8:7})});document.getElementById('ge-stage-name').textContent=s.name;
  render();state.textContent='戦闘開始';hint.textContent='青い領地を選択';
  timer=setInterval(grow,1100);aiTimer=setInterval(ai,s.speed+900);marchTimer=setInterval(()=>{if(movements.length)render()},250);
 }
 function render(anim=-1,klass=''){board.innerHTML='';const counts={b:0,r:0,y:0,p:0};cells.forEach((c,i)=>{if(counts[c.o]!==undefined)counts[c.o]++;const incoming=movements.filter(m=>m.to===i),b=document.createElement('button'),land=c.o!=='w',target=selected>=0&&land&&neighbors(selected).includes(i),ownerClass={b:'blue',r:'red',y:'yellow',p:'purple'}[c.o]||'';b.className='ge-cell '+(land?'land '+c.t:'water')+(ownerClass?' '+ownerClass:'')+(c.c?' capital':'')+(i===selected?' selected':'')+(target?' target':'')+(incoming.length?' incoming':'')+(i===anim?' '+klass:'');b.disabled=!land;b.setAttribute('aria-label',land?`兵力 ${c.p}`:'海');if(land){b.innerHTML='<span class="ge-power">'+c.p+'</span>';if(incoming.length){const left=Math.max(1,Math.ceil((Math.min(...incoming.map(m=>m.arrive))-Date.now())/1000));b.innerHTML+='<span class="ge-march">➜ '+incoming.reduce((n,m)=>n+m.force,0)+' · '+left+'秒</span>'}b.onpointerdown=e=>{e.preventDefault();tap(i)}}board.appendChild(b)});document.getElementById('ge-blue').textContent=counts.b;document.getElementById('ge-red').textContent=ARMIES.slice(1,playerCount).filter(o=>!defeated.has(o)).length;document.getElementById('ge-factions').innerHTML=ARMIES.slice(1,playerCount).map(o=>'<span class="'+o+'">'+({r:'赤軍',y:'黄軍',p:'紫軍'}[o])+' '+counts[o]+'</span>').join('')}
 function tap(i){if(ended||cells[i].o==='w')return;const c=cells[i];if(selected===i){selected=-1;state.textContent='選択解除';hint.textContent='青い領地を選択';render();return}if(selected>=0&&neighbors(selected).includes(i)){const from=selected;selected=-1;if(!attack(from,i,'b')){state.textContent='出撃準備中';hint.textContent='同じ領地からの連続出撃はできません';render()}return}if(c.o==='b'){selected=i;state.textContent='兵力 '+c.p;hint.textContent='隣の領地へ侵攻・移動';render();return}}
 function attack(from,to,owner){const a=cells[from];if(a.o!==owner||a.p<2||Date.now()<(cooldowns[from]||0)||movements.some(m=>m.from===from))return false;const share=owner==='b'?ratio:.55,force=Math.max(1,Math.floor(a.p*share)),token=gameToken,travel=3000;a.p-=force;cooldowns[from]=Date.now()+travel+1800;const move={from,to,owner,force,arrive:Date.now()+travel};movements.push(move);if(owner==='b'){state.textContent='部隊が進軍中';hint.textContent=force+'人 · 約3秒で到着'}render();setTimeout(()=>{if(token!==gameToken||ended)return;movements=movements.filter(m=>m!==move);resolve(move);render(to,'claim')},travel);return true}
 function resolve(move){const d=cells[move.to];if(d.o===move.owner){d.p=Math.min(999,d.p+move.force);return}if(move.force>d.p){const oldCapital=d.c?d.co:'';d.o=move.owner;d.p=move.force-d.p;if(oldCapital){defeated.add(oldCapital);d.c=false;d.co='';cells.forEach(c=>{if(c.o===oldCapital)c.o=move.owner});movements=movements.filter(m=>m.owner!==oldCapital);if(oldCapital==='b'){finish(move.owner);return}const enemies=ARMIES.slice(1,playerCount);if(move.owner==='b'&&enemies.every(o=>defeated.has(o)))finish('b')}}else d.p-=move.force}
 function grow(){if(ended)return;cells.forEach(c=>{if((c.o==='b'||c.o==='r')&&c.p<99)c.p+=c.c||c.t==='city'?2:1});render()}
 function ai(){if(ended)return;const active=ARMIES.slice(1,playerCount).filter(o=>!defeated.has(o));if(!active.length)return;const owner=active[aiTurn++%active.length],frontier=[];cells.forEach((c,i)=>{if(c.o===owner&&c.p>3&&!movements.some(m=>m.from===i)){const opts=neighbors(i).filter(n=>cells[n].o!==owner&&cells[n].o!=='w');if(opts.length)frontier.push([i,opts])}});if(!frontier.length)return;frontier.sort((a,b)=>cells[b[0]].p-cells[a[0]].p);const pick=frontier[Math.floor(Math.random()*Math.min(3,frontier.length))],targets=pick[1].sort((a,b)=>(cells[a].p+(cells[a].o==='b'?-3:0))-(cells[b].p+(cells[b].o==='b'?-3:0)));attack(pick[0],targets[0],owner)}
 function finish(winner){ended=true;clearInterval(timer);clearInterval(aiTimer);clearInterval(marchTimer);document.getElementById('ge-result').textContent=winner==='b'?'勝利！':'敗北…';document.getElementById('ge-result-sub').textContent=winner==='b'?'敵の首都を制圧しました':'自軍の首都が奪われました';document.getElementById('ge-modal').classList.add('show')}
 document.querySelectorAll('[data-players]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();playerCount=Number(b.dataset.players);document.querySelectorAll('[data-players]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-ratio]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();ratio=Number(b.dataset.ratio);document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-stage]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();startStage(b.dataset.stage)});document.getElementById('ge-home-button').onclick=showHome;document.getElementById('ge-restart').onclick=init;document.getElementById('ge-again').onclick=()=>{document.getElementById('ge-modal').classList.remove('show');init()};document.getElementById('ge-stage-select').onclick=showHome;showHome();
}, 150);
</script>
'''


MAP_GAME_JS = r'''
<script>
setTimeout(()=>{
 const ARMIES=['b','r','y','p'],COLORS={b:'blue',r:'red',y:'yellow',p:'purple'},NAMES={r:'赤軍',y:'黄軍',p:'紫軍'};
 const REGIONS=[
  {p:'25,55 120,30 145,110 70,145 20,110',c:[78,86],t:'forest',n:'北西林'},
  {p:'120,30 240,25 250,105 145,110',c:[187,68],t:'plain',n:'北原'},
  {p:'240,25 365,45 350,125 250,105',c:[303,76],t:'mountain',n:'白峰'},
  {p:'365,45 490,25 515,105 430,145 350,125',c:[430,82],t:'city',n:'王都道'},
  {p:'490,25 610,40 625,125 515,105',c:[559,72],t:'plain',n:'東原'},
  {p:'610,40 765,60 755,145 625,125',c:[689,88],t:'port',n:'北港'},
  {p:'20,110 70,145 60,250 15,270',c:[42,190],t:'port',n:'西岬'},
  {p:'70,145 145,110 250,105 235,220 145,245 60,250',c:[151,179],t:'forest',n:'深緑森'},
  {p:'250,105 350,125 345,235 235,220',c:[295,172],t:'plain',n:'中央野'},
  {p:'350,125 430,145 515,105 530,215 435,250 345,235',c:[438,181],t:'city',n:'中央都'},
  {p:'515,105 625,125 620,240 530,215',c:[575,170],t:'mountain',n:'東山地'},
  {p:'625,125 755,145 780,260 620,240',c:[698,193],t:'port',n:'東海岸'},
  {p:'15,270 60,250 145,245 160,375 70,410 20,365',c:[82,320],t:'plain',n:'西平野'},
  {p:'145,245 235,220 345,235 335,360 240,395 160,375',c:[245,306],t:'city',n:'交易都'},
  {p:'345,235 435,250 530,215 525,350 430,390 335,360',c:[433,306],t:'forest',n:'南森林'},
  {p:'530,215 620,240 780,260 760,375 635,405 525,350',c:[651,310],t:'plain',n:'東平野'},
  {p:'70,410 160,375 240,395 275,485 125,495',c:[175,445],t:'port',n:'南西港'},
  {p:'240,395 335,360 430,390 525,350 635,405 575,490 410,480 275,485',c:[430,432],t:'mountain',n:'南大地'}
 ];
 const LINKS=[[0,1],[0,6],[0,7],[1,2],[1,7],[2,3],[2,7],[2,8],[3,4],[3,8],[3,9],[4,5],[4,9],[4,10],[5,10],[5,11],[6,7],[6,12],[7,8],[7,12],[7,13],[8,9],[8,13],[8,14],[9,10],[9,14],[10,11],[10,14],[10,15],[11,15],[12,13],[12,16],[13,14],[13,16],[13,17],[14,15],[14,17],[15,17],[16,17]];
 const SEA_LINKS=[[5,16],[6,11]],ADJ=REGIONS.map(()=>[]);[...LINKS,...SEA_LINKS].forEach(([a,b])=>{ADJ[a].push(b);ADJ[b].push(a)});
 const STAGES=[{name:'STAGE 01 · はじまりの島',power:16,speed:2200},{name:'STAGE 02 · 分断海峡',power:20,speed:1900},{name:'STAGE 03 · 決戦大陸',power:25,speed:1650}],STARTS=[[16,12,13],[5,4,11],[0,1,6],[15,10,17]];
 let cells=[],selected=-1,timer=null,aiTimer=null,marchTimer=null,ended=true,stageIndex=0,playerCount=2,ratio=.5,movements=[],cooldowns={},token=0,aiTurn=0,defeated=new Set();
 const board=document.getElementById('ge-board'),state=document.getElementById('ge-state'),hint=document.getElementById('ge-hint'),home=document.getElementById('ge-home'),game=document.getElementById('ge-game');
 const icon=t=>({forest:'♣',mountain:'▲',city:'◆',port:'⚓',plain:'•'}[t]);
 function stop(){token++;clearInterval(timer);clearInterval(aiTimer);clearInterval(marchTimer);movements=[]}
 function showHome(){stop();ended=true;document.getElementById('ge-modal').classList.remove('show');game.style.display='none';home.style.display='block'}
 function startStage(i){stageIndex=Number(i);home.style.display='none';game.style.display='block';init()}
 function init(){stop();const s=STAGES[stageIndex];ended=false;selected=-1;cooldowns={};defeated=new Set();aiTurn=0;cells=REGIONS.map((r,i)=>({o:'n',p:2+(i*3%5),c:false,co:'',t:r.t}));ARMIES.slice(0,playerCount).forEach((o,k)=>{const z=STARTS[k];Object.assign(cells[z[0]],{o,p:k?s.power:16,c:true,co:o});Object.assign(cells[z[1]],{o,p:k?8:7});Object.assign(cells[z[2]],{o,p:k?8:7})});document.getElementById('ge-stage-name').textContent=s.name;state.textContent='戦闘開始';hint.textContent='青い地域を選択';render();timer=setInterval(grow,1300);aiTimer=setInterval(ai,s.speed);marchTimer=setInterval(()=>movements.length&&render(),250)}
 function supplied(owner){const cap=cells.findIndex(c=>c.o===owner&&c.c);if(cap<0)return new Set();const seen=new Set([cap]),q=[cap];while(q.length){const i=q.shift();ADJ[i].forEach(n=>{if(cells[n].o===owner&&!seen.has(n)){seen.add(n);q.push(n)}})}return seen}
 function render(){const counts={b:0,r:0,y:0,p:0},supply={};ARMIES.slice(0,playerCount).forEach(o=>supply[o]=supplied(o));const roads=LINKS.map(([a,b])=>`<line class="ge-road" x1="${REGIONS[a].c[0]}" y1="${REGIONS[a].c[1]}" x2="${REGIONS[b].c[0]}" y2="${REGIONS[b].c[1]}"/>`).join(''),sea=SEA_LINKS.map(([a,b])=>`<line class="ge-sea-road" x1="${REGIONS[a].c[0]}" y1="${REGIONS[a].c[1]}" x2="${REGIONS[b].c[0]}" y2="${REGIONS[b].c[1]}"/>`).join('');let areas='';cells.forEach((c,i)=>{if(counts[c.o]!==undefined)counts[c.o]++;const r=REGIONS[i],target=selected>=0&&ADJ[selected].includes(i),cls=COLORS[c.o]||'neutral',unsupplied=ARMIES.includes(c.o)&&!supply[c.o]?.has(i),fog=c.o!=='b'&&c.t==='forest'&&!ADJ[i].some(n=>cells[n].o==='b'),shown=fog?'?':c.p;areas+=`<g class="ge-region ${cls}${i===selected?' selected':''}${target?' target':''}${unsupplied?' unsupplied':''}${fog?' fog':''}" data-region="${i}"><polygon points="${r.p}"/><text class="ge-terrain" x="${r.c[0]-24}" y="${r.c[1]-19}">${icon(c.t)}</text><text class="ge-place" x="${r.c[0]}" y="${r.c[1]+27}">${r.n}</text><circle cx="${r.c[0]}" cy="${r.c[1]}" r="22" fill="#07111dcc"/><text class="ge-region-label" x="${r.c[0]}" y="${r.c[1]}">${shown}</text>${c.c?`<text class="ge-capital" x="${r.c[0]+26}" y="${r.c[1]-20}">★</text>`:''}${unsupplied?`<text class="ge-supply" x="${r.c[0]}" y="${r.c[1]+43}">⚠ 補給切れ</text>`:''}</g>`});const moves=movements.map(m=>{const a=REGIONS[m.from].c,b=REGIONS[m.to].c,x=(a[0]+b[0])/2,y=(a[1]+b[1])/2,left=Math.max(1,Math.ceil((m.arrive-Date.now())/1000));return `<g><line class="ge-move-line" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/><rect class="ge-move-badge" x="${x-30}" y="${y-12}" width="60" height="24" rx="12"/><text class="ge-move-text" x="${x}" y="${y}">${m.force} · ${left}秒</text></g>`}).join('');board.innerHTML=`<svg class="ge-map" viewBox="0 0 800 520">${areas}${roads}${sea}${moves}</svg>`;board.querySelectorAll('[data-region]').forEach(g=>g.onpointerdown=e=>{e.preventDefault();tap(Number(g.dataset.region))});document.getElementById('ge-blue').textContent=counts.b;document.getElementById('ge-red').textContent=ARMIES.slice(1,playerCount).filter(o=>!defeated.has(o)).length;document.getElementById('ge-factions').innerHTML=ARMIES.slice(1,playerCount).map(o=>`<span class="${o}">${NAMES[o]} ${counts[o]}</span>`).join('')}
 function tap(i){if(ended)return;const c=cells[i];if(selected===i){selected=-1;render();return}if(selected>=0&&ADJ[selected].includes(i)){const from=selected;selected=-1;if(!attack(from,i,'b')){state.textContent='出撃準備中';hint.textContent='この地域からはまだ出撃できません';render()}return}if(c.o==='b'){selected=i;state.textContent=REGIONS[i].n+' · 兵力 '+c.p;const note={mountain:'山岳防御＋50%',city:'都市は兵力成長＋1',forest:'森は敵から兵力を隠す',port:'港から海上進軍可能',plain:'道路でつながる地域へ進軍'}[c.t];hint.textContent=(supplied('b').has(i)?note:'⚠ 補給切れ · 兵力成長停止');render()}}
 function attack(from,to,owner){const a=cells[from];if(a.o!==owner||a.p<2||Date.now()<(cooldowns[from]||0)||movements.some(m=>m.from===from))return false;const force=Math.max(1,Math.floor(a.p*(owner==='b'?ratio:.55))),isSea=SEA_LINKS.some(([x,y])=>(x===from&&y===to)||(x===to&&y===from)),travel=isSea?4600:3400,myToken=token;a.p-=force;cooldowns[from]=Date.now()+travel+1800;const m={from,to,owner,force,arrive:Date.now()+travel};movements.push(m);if(owner==='b'){state.textContent=isSea?'海路を進軍中':'道路を進軍中';hint.textContent=force+'人 · 約'+Math.ceil(travel/1000)+'秒で到着'}render();setTimeout(()=>{if(myToken!==token||ended)return;movements=movements.filter(x=>x!==m);resolve(m);render()},travel);return true}
 function resolve(m){const d=cells[m.to];if(d.o===m.owner){d.p=Math.min(999,d.p+m.force);return}const defense=d.t==='mountain'?Math.ceil(d.p*1.5):d.p;if(m.force>defense){const old=d.c?d.co:'';d.o=m.owner;d.p=m.force-defense;if(old){defeated.add(old);d.c=false;d.co='';cells.forEach(c=>{if(c.o===old)c.o=m.owner});movements=movements.filter(x=>x.owner!==old);if(old==='b'){finish(m.owner);return}if(m.owner==='b'&&ARMIES.slice(1,playerCount).every(o=>defeated.has(o)))finish('b')}}else d.p=Math.max(0,d.p-Math.ceil(m.force/(d.t==='mountain'?1.5:1)))}
 function grow(){if(ended)return;const supply={};ARMIES.slice(0,playerCount).forEach(o=>supply[o]=supplied(o));cells.forEach((c,i)=>{if(ARMIES.includes(c.o)&&supply[c.o]?.has(i)&&c.p<99)c.p+=c.c||c.t==='city'?2:1});render()}
 function ai(){if(ended)return;const active=ARMIES.slice(1,playerCount).filter(o=>!defeated.has(o));if(!active.length)return;const owner=active[aiTurn++%active.length],front=[];cells.forEach((c,i)=>{if(c.o===owner&&c.p>3&&!movements.some(m=>m.from===i)){const opts=ADJ[i].filter(n=>cells[n].o!==owner);if(opts.length)front.push([i,opts])}});if(!front.length)return;front.sort((a,b)=>cells[b[0]].p-cells[a[0]].p);const pick=front[Math.floor(Math.random()*Math.min(3,front.length))],targets=pick[1].sort((a,b)=>(cells[a].p+(cells[a].o==='b'?-3:0))-(cells[b].p+(cells[b].o==='b'?-3:0)));attack(pick[0],targets[0],owner)}
 function finish(w){ended=true;clearInterval(timer);clearInterval(aiTimer);clearInterval(marchTimer);document.getElementById('ge-result').textContent=w==='b'?'勝利！':'敗北…';document.getElementById('ge-result-sub').textContent=w==='b'?'すべての敵首都を制圧しました':'自軍の首都が奪われました';document.getElementById('ge-modal').classList.add('show')}
 document.querySelectorAll('[data-players]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();playerCount=Number(b.dataset.players);document.querySelectorAll('[data-players]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-ratio]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();ratio=Number(b.dataset.ratio);document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-stage]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();startStage(b.dataset.stage)});document.getElementById('ge-home-button').onclick=showHome;document.getElementById('ge-restart').onclick=init;document.getElementById('ge-again').onclick=()=>{document.getElementById('ge-modal').classList.remove('show');init()};document.getElementById('ge-stage-select').onclick=showHome;showHome();
},150);
</script>
'''


@ui.page('/grid-empire')
def grid_empire_page():
    if not require_app_access('grid_empire'):
        return
    Theme.page('GRID EMPIRE', app_name='grid-empire')
    ui.add_head_html(GAME_CSS)
    ui.html(GAME_HTML, sanitize=False)
    ui.add_body_html(MAP_GAME_JS)
